### ISSUE TITLE
Make the Canvas Responsive

### ISSUE THREAD

**Issue by rksingh2001** [rksingh2001/scribbli#3]
1. The Canvas should resize according to screen size.
2. The Canvas should maintain the aspect ratio of 8:5
3. The Mouse Coordinates would need to be transformed into a common standard by the emitter, and then converted to their respective sizes by all the different clients.

**Comment by tanpreetjolly** [comment]
Can i take up the issue

**Comment by rksingh2001** [comment]
Yes, I am assigning it to you @tanpreetjolly
